#
# obs-vaapi. OBS Studio plugin.
# Copyright (C) 2022 Florian Zwoch <fzwoch@gmail.com>
#
# This file is part of obs-vaapi.
#
# obs-vaapi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# obs-vaapi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with obs-vaapi. If not, see <http://www.gnu.org/licenses/>.
#

build:
  stage: build
  image: registry.gitlab.com/fzwoch/obs-vaapi
  script:
    - meson x86_64 -Dlibobs=disabled -Dc_args=-I/obs/libobs -Dc_link_args="-Wl,--unresolved-symbols=ignore-all -static-libgcc"
    - ninja -C x86_64

    - echo "[binaries]" > arm64.txt
    - echo "c = 'aarch64-linux-gnu-gcc'" >> arm64.txt
    - echo "strip = 'aarch64-linux-gnu-strip'" >> arm64.txt
    - echo "pkgconfig = 'aarch64-linux-gnu-pkg-config'" >> arm64.txt
    - echo "" >> arm64.txt
    - echo "[host_machine]" >> arm64.txt
    - echo "system = 'linux'" >> arm64.txt
    - echo "cpu_family = 'aarch64'" >> arm64.txt
    - echo "cpu = 'aarch64'" >> arm64.txt
    - echo "endian = 'little'" >> arm64.txt

    - meson aarch64 --cross-file=arm64.txt -Dlibobs=disabled -Dc_args=-I/obs/libobs -Dc_link_args="-Wl,--unresolved-symbols=ignore-all -static-libgcc"
    - ninja -C aarch64
  artifacts:
    name: obs-vaapi
    paths:
      - x86_64/*.so
      - aarch64/*.so
