on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/fzwoch/obs-vaapi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build x86_64
        run: |
          meson setup --buildtype=release -Dlibobs=disabled -Dc_args=-I/obs -Dc_link_args='-Wl,--unresolved-symbols=ignore-all -static-libgcc' x86_64
          meson compile -C x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: obs-vaapi
          path: |
            x86_64/*.so
